[package]
name = "cel"
version = "0.1.0"
edition = "2021"

[lib]
name = "cel"
path = "src/lib.rs"

[[bin]]
name = "cel"
path = "src/cel.rs"
required-features = ["clap"]

[dependencies]
clap = { version = "3.0.0-rc.9", features = ["derive"], optional = true }
